---
#################################################################
# DHT11 Temperature and Humidity Sensor
#################################################################
platform: dht
pin: D7
model: DHT11
update_interval: ${update_interval}
temperature:
  name: ${name} Temperature
  filters:
    - sliding_window_moving_average:
        window_size: ${sliding_window}
        send_every: ${sliding_window}
        send_first_at: 1
humidity:
  name: ${name} Humidity
  filters:
    - sliding_window_moving_average:
        window_size: ${sliding_window}
        send_every: ${sliding_window}
        send_first_at: 1