---
platform: template
name: ${name} Uptime Formatted
lambda: |-
  int time = (id(sensor_uptime).state);
  int days = time / (24 * 3600);
  time = time % (24 * 3600); 
  int hours = time / 3600;
  time = time % 3600;
  int minutes = time /  60;
  return { (String(days) +"d " + String(hours) +"h " + String(minutes) +"m").c_str() };
icon: mdi:clock-start
update_interval: 60s