#################################################################
# Sensor on Analog Pin A0
#################################################################
---
platform: adc
name: ${name} A0
pin: A0
id: ${device}_a0
update_interval: ${update_interval}
unit_of_measurement: ${adc_unit_of_measurement}
icon: ${adc_icon}
accuracy_decimals: ${adc_accuracy_decimals}
filters:
  - filter_out: nan
  - multiply: 3.3
  # - !include filter/sliding_window.yaml
  - !include lambda/a0_moisture_result.yaml
<<: !include lambda/a0_moisture_action.yaml
