################################################################
# ADS1115 Analog multiplexer.
################################################################
# Virtual A0
platform: ads1115
name: ADS1115 A0 ${name}
multiplexer: 'A0_GND'
id: ${device}_va0
unit_of_measurement: ${adc_a0_unit_of_measurement}
icon: ${adc_va0_icon}
accuracy_decimals: ${adc_a0_accuracy_decimals}
gain: ${adc_gain}
update_interval: ${update_interval_short}
filters:
  - !include filter/sliding_window.yaml
  - !include lambda/a0_moisture_result.yaml
on_value:
  then:
    - lambda: |-
        if ( id(${device}_va0).raw_state < id(sensor_open_value) ){
          auto call = id(va0_status_led).turn_off();
          call.perform();  
        } else if (x < id(danger_threshold) ) {
          auto call = id(va0_status_led).turn_on();
          call.set_brightness(id(led_max_brightness));
          call.set_effect("Danger Will Robinson");
          call.perform();  
        } else {
          auto call = id(va0_status_led).turn_on();
          call.set_brightness(id(led_max_brightness));
          call.set_effect("none");
          call.set_rgb((100.0-id(${device}_va0).state)/100.0, id(${device}_va0).state/100.0, 0.0);
          call.perform();  
        }

### END OF ADS115 BLOCK