################################################################
# ADS1115 Analog multiplexer.
################################################################
---
# Virtual A2
platform: ads1115
name: ADS1115 A2 ${name}
multiplexer: 'A2_GND'
id: ${device}_va2
unit_of_measurement: ${adc_unit_of_measurement}
icon: ${adc_icon}
accuracy_decimals: ${adc_accuracy_decimals}
gain: ${adc_gain}
update_interval: ${update_interval}
filters:
  - filter_out: nan
  # - !include filter/sliding_window.yaml
  - !include lambda/ads1115_moisture_result.yaml
on_value:
  then:
    - lambda: |-
        // ESP_LOGD("main", "VA2 val (x): %f", x );
        if ( id(${device}_va2).raw_state < id(adc_nc_value)  )
        {
          auto call = id(va2_status_led).turn_off();
          call.perform();  
        } else if (x < id(danger_threshold) ) {
          auto call = id(va2_status_led).turn_on();
          call.set_brightness(id(led_max_brightness));
          call.set_effect("Danger Will Robinson");
          call.perform();  
        } else {
          auto call = id(va2_status_led).turn_on();
          call.set_brightness(id(led_max_brightness));
          call.set_effect("none");
          call.set_rgb( (100.0-x)/100.0, x/100.0, 0.0 );
          call.perform();  
        }
  
### END OF ADS115 BLOCK