---
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: ${reboot_timeout}
  ap:
    ssid: ${device}
    password: !secret ap_wifi_password
  # on_value:
  # if:
  #   condition:
  #     wifi.connected:
  #   then:
  #     - logger.log yah!!!!!
captive_portal:
