#################################################################
# Sensor lambda result on Analog Pin A
# Voltage at which the sensor is reading not connected
#    - id: adc_nc_value
#      type: float
#      restore_value: no
#      initial_value: '0.05'
#    # It's the value in satuated soil 
#    - id: adc_soil_saturated
#      type: float
#      restore_value: no
#      initial_value: '0.70'
#    # Max voltage (including multiplier). The highter the drier
#    - id: adc_soil_dry
#      type: float
#      restore_value: no
#      initial_value: '2.3' with no multiplier '0.26'
#################################################################
---
lambda: |-
        ESP_LOGD("main", "A0 val: %f", x );

        if ( x > 0.7 || x < 0.5) return 0;
        else if (x < 0.26 ) return 100;
        else return (0.7-x)/(0.7-0.26)*100.0;
