#################################################################
# Sensor on Analog Pin A0 - Actions
#  # Voltage at which the sensor is reading not connected
#  - id: adc_nc_value
#    type: float
#    restore_value: no
#    initial_value: '0.05'
#################################################################
---
on_value:
  then:
    lambda: |-
          ESP_LOGD("main", "A0 val (x): %f", x );
          if ( id(${device}_a0).raw_state < 0.05  )
          {
            auto call = id(a0_status_led).turn_off();
            call.perform();
          } else if (x < id(danger_threshold) ) {
            auto call = id(a0_status_led).turn_on();
            call.set_brightness(id(led_max_brightness));
            call.set_effect("Danger Will Robinson");
            call.perform();  
          } else {
            auto call = id(a0_status_led).turn_on();
            call.set_brightness(id(led_max_brightness));
            call.set_effect("none");
            call.set_rgb( (100.0-x)/100.0, x/100.0, 0.0 );
            call.perform();  
          }
