#################################################################
# ADS1115 Sensor lambda result on I2C
#  # It's the value in satuated soil 
#  - id: ads1115_soil_saturated
#    type: float
#    restore_value: no
#    initial_value: '1.0'

#  # Max voltage (including multiplier). The highter the drier
#  - id: ads1115_soil_dry
#    type: float
#    restore_value: no
#    initial_value: '2.04' with gain
#################################################################
---
lambda: |-
        ESP_LOGD("main", "ADS1115 val: %f", x );

        if ( x > 2.04 || x < 0.5  ) return 0;
        else if (x < 1.00 ) return 100;
        else return (2.04 - x)/(2.04 - 1.00)*100.0;
