#################################################################
# Flash the status LED until we get a good connection
#################################################################
---
interval: 10s
then:
  if:
    condition:
      wifi.connected:
    then:
      - lambda: |-
          float absVal = std::abs( id(${device}_wifi_signal).state );
          ESP_LOGD("main", "Connected: Wifi Signal:%f", absVal );
          auto call = id(status_led).turn_on();
          call.set_brightness(0.3);
          call.set_effect("none");
          call.set_rgb( (100-absVal)/100.0, 0.0, absVal/100.0 );
          call.perform();  
    else:
      - logger.log: "Lost Wifi Connection. Strobe the status led"
      - light.turn_on:
          id: status_led
          brightness: 30%
          effect: Wifi Connecting
