substitutions:
  device: four_channel_relay
  name: Four Channel Relay
  location: Test
  reboot_timeout: 1h
  update_interval: 10min
  update_interval_memory_usage: 5s
  update_interval_wifi_status: 30min
  update_interval_short: 10s
  sliding_window: "4"
  adc_pin: A0
  logger_baud_rate: "0" # turn on logging to use uart
  uart_baud_rate: "115200" # turn on logging to use uart
  uart_tx_pin: GPIO1
  uart_rx_pin: GPIO3

esphome:
  name:  ${device}
  platform: ESP8266
  board: esp01_1m

<<: !include common/uart.yaml

<<: !include common/wifi.yaml
<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/text_sensors.yaml
<<: !include common/logger.yaml
<<: !include common/binary_sensors.yaml

#################################################################
# Sensor Configuration
#################################################################
sensor:
  - !include common/sensor/wifi-signal.yaml
  - !include common/sensor/uptime.yaml

#################################################################
# Misc setup
#################################################################
switch:
   - !include common/switch/restart.yaml
   - platform: template
     name: 'Relay 1'
     id: relay1
     turn_on_action:
       - uart.write: [0xA0, 0x01, 0x01, 0xA2]
     turn_off_action:
       - uart.write: [0xA0, 0x01, 0x00, 0xA1]
     optimistic: true
   - platform: template
     name: 'Relay 2'
     id: relay2
     turn_on_action:
       - uart.write: [0xA0, 0x02, 0x01, 0xA3]
     turn_off_action:
       - uart.write: [0xA0, 0x02, 0x00, 0xA2]
     optimistic: true
   - platform: template
     name: 'Relay 3'
     id: relay3
     turn_on_action:
       - uart.write: [0xA0, 0x03, 0x01, 0xA4]
     turn_off_action:
       - uart.write: [0xA0, 0x03, 0x00, 0xA3]
     optimistic: true
   - platform: template
     name: 'Relay 4'
     id: relay4
     turn_on_action:
       - uart.write: [0xA0, 0x04, 0x01, 0xA5]
     turn_off_action:
       - uart.write: [0xA0, 0x04, 0x00, 0xA4]
     optimistic: true