substitutions:
  device: moisture_sensor_prototype
  name: Moisture Sensor Prototype
  location: Test
  reboot_timeout: 1h
  update_interval: 10min
  update_interval_short: 10s
  sliding_window: "15"
  i2c_sda: D2
  i2c_scl: D1
  i2c_scan: 'True'
  i2c_device: ads115_a
  ads_address: '0x48'
  adc_a0_icon: "mdi:water-percent"
  adc_a0_accuracy_decimals: '1'
  adc_a0_unit_of_measurement: "%"
  adc_va0_icon: "mdi:water-percent"
  adc_gain: '0.256'

esphome:
  name: ${device}
  platform: ESP8266
  board: d1_mini


<<: !include common/common.yaml
<<: !include common/logger.yaml
<<: !include common/binary_sensors.yaml
<<: !include common/switches.yaml

#
# I2C Iniitalisation
#
<<: !include common/i2c.yaml
<<: !include common/analog_sensor/ads1115.yaml
    
globals:
   - id: sensor_open_value
     type: float
     restore_value: no
     initial_value: '0.01'
   - id: led_max_brightness
     type: float
     restore_value: no
     initial_value: '0.5'
   - id: a0_air
     type: float
     restore_value: no
     initial_value: '0.7'
   - id: a0_water
     type: float
     restore_value: no
     initial_value: '0.26'
   - id: a0_gnd_air
     type: float
     restore_value: no
     initial_value: '0.0316'
   - id: a0_gnd_water
     type: float
     restore_value: no
     initial_value: '0.217'
   # Go below this and soil is too dry
   - id: danger_threshold
     type: float
     restore_value: no
     initial_value: '30.0'

#################################################################
# Various Sensor Config
#################################################################

#################################################################
# Sensor Configuration
#################################################################

sensor:
  - !include common/sensor/wifi-signal.yaml
  - !include common/sensor/uptime.yaml
  - !include common/sensor/dht11.yaml
  # Soil Sensore on Analog Pin A0
  - !include common/analog_sensor/adc_a0.yaml

### END OF SENSOR CONFIG BLOCK

################################################################
# ADS1115 Analog multiplexer.
################################################################
# Virtual A0
  - platform: ads1115
    name: ADS1115 A0 ${name}
    multiplexer: 'A0_GND'
    id: ${device}_va0
    unit_of_measurement: ${adc_a0_unit_of_measurement}
    icon: ${adc_va0_icon}
    accuracy_decimals: ${adc_a0_accuracy_decimals}
    gain: ${adc_gain}
    update_interval: ${update_interval_short}
    filters:
      # - sliding_window_moving_average:
      #     window_size:  ${sliding_window}
      #     send_every:  ${sliding_window}
      #     send_first_at: 1
      - lambda: |-
          if (x < id(a0_gnd_air)) {
            return 0.0;
          } else if (x > id(a0_gnd_water)) {
            return 100.0;
          } else {
            return (x - id(a0_gnd_air)) / (id(a0_gnd_water)-id(a0_gnd_air)) * 100.0;
          }
    on_value:
      then:
        - lambda: |-
            if ( id(${device}_va0).raw_state < id(sensor_open_value) ){
              auto call = id(va0_status_led).turn_off();
              call.perform();  
            } else if (x < id(danger_threshold) ) {
              auto call = id(va0_status_led).turn_on();
              call.set_brightness(id(led_max_brightness));
              call.set_effect("Danger Will Robinson");
              call.perform();  
            } else {
              auto call = id(va0_status_led).turn_on();
              call.set_brightness(id(led_max_brightness));
              call.set_effect("none");
              call.set_rgb((100.0-id(${device}_va0).state)/100.0, id(${device}_va0).state/100.0, 0.0);
              call.perform();  
            }

### END OF ADS115 BLOCK

#################################################################
# GRB WS2812B LED lights. PIN D5
#################################################################
light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D5
    num_leds: 6
    rgb_order: GRB
    name: "FastLED WS2812B Light"
    id: led_strip
# Soil Sensor on ESP A0
  - platform: partition
    name: "A0 Led"
    id: a0_status_led
    effects:
      - strobe:
          name: Danger Will Robinson
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
            - state: False
              duration: 500ms
    segments:
      - id: led_strip
        from: 0
        to: 0
# Soil Sensor on AD1115 A0-GND
  - platform: partition
    name: "VA0 Led"
    id: va0_status_led
    effects:
      - strobe:
          name: Danger Will Robinson
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
            - state: False
              duration: 500ms
    segments:
      - id: led_strip
        from: 1
        to: 1
# Soil Sensor on AD1115 A1-GND
  - platform: partition
    name: "VA1 Led"
    id: va1_status_led
    effects:
      - strobe:
          name: Danger Will Robinson
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
            - state: False
              duration: 500ms
    segments:
      - id: led_strip
        from: 2
        to: 2
# Soil Sensor on AD1115 A2-GND
  - platform: partition
    name: "VA2 Led"
    id: va2_status_led
    effects:
      - strobe:
          name: Danger Will Robinson
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
            - state: False
              duration: 500ms
    segments:
      - id: led_strip
        from: 3
        to: 3
# Soil Sensor on AD1115 A3-GND
  - platform: partition
    name: "VA3 Led"
    id: va3_status_led
    effects:
      - strobe:
          name: Danger Will Robinson
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
            - state: False
              duration: 500ms
    segments:
      - id: led_strip
        from: 4
        to: 4
# Status LED
  - platform: partition
    name: "led6"
    id: section6
    segments:
      - id: led_strip
        from: 5
        to: 5
### END OF LED LIGHT (WS2812B) BLOCK

#################################################################
# Misc setup
#################################################################
switch:
  - !include common/switch/restart.yaml

#################################################################
# List of fonts we are using for the OLED Display.
#################################################################
font:
  - file: 'ttf/arial.ttf'
    id: font_arial
    size: 10
  - file: 'ttf/times.ttf'
    id: font_times
    size: 16
  - file: 'ttf/MiriamMonoCLM-Bold.ttf'
    id: font_miriam
    size: 24
    
#################################################################
# OLED Display Configuration
#################################################################
# Cycle through pages on a timer
# interval:
#   - interval: 5s
#     then:
#       - display.page.show_next: oled_display
#       - component.update: oled_display

# Setup Display to show sensor reading in real time.
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: D0
    address: 0x3C
    id: oled_display
    
    pages:
      - id: page1
        lambda: |-
          static int num_sensors = 5;
          static int disp_width = it.get_width();
          static int disp_height = it.get_height();
          static int badge_center = disp_width/(num_sensors*2);
          static int badge_width = badge_center*2;
          static int badge_padding = 2;
          static int badge_radius = badge_center - badge_padding;
          static int badge_y_offset = 40;
          static int badge_x_offset = 4;
          static int badge_name_pos = badge_y_offset - badge_radius - 6;

          it.print(0, 0, id(font_times), "Rosies Planter Box");
          // Display Wifi, temp and humidity here and the a line.

          // Display each sensor in it's own little circle
          int i = 0;
          char str[10];
          // TEST
          sprintf( str, "%2.0f", id( ${device}_a0 ).state);
          it.circle(badge_center + (badge_width * i), badge_y_offset, badge_radius);
          it.printf(badge_center + (badge_width * i), badge_name_pos, id(font_arial), TextAlign::CENTER, "S%d", i + 1);
          it.printf(badge_center + (badge_width * i), badge_y_offset, id(font_arial), TextAlign::CENTER, "%s", id(${device}_a0).raw_state < id(sensor_open_value) ? "Off": str);
      - id: page2
        lambda: |-
          it.print(0, 0, id(font_times), "Rosies Planter Box");
          
          // Print time in HH:MM format
          it.strftime(0, 16, id(font_miriam), TextAlign::TOP_LEFT, "%l:%M  %P", id(esptime).now());
#      - id: page3
#        lambda: |-
#          it.printf(0, 10, id(font_arial), "Sun: %s", id(sun).state.c_str());
#          // it.printf(0, 16, id(font_arial), "Elev: %s", id(sun).sunset());
